# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
target 'ssstrangersoccer' do
  pod 'Stripe', '~> 11.2.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ssstrangersoccer


  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  pod 'Yoga', path: "#{rn_path}/ReactCommon/yoga/Yoga.podspec"
  pod 'Firebase/Messaging'
  pod 'GoogleSignIn'
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTWebSocket',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'BatchedBridge',
    'RCTVibration',
  ]

  #pod 'react-native-maps', path: rn_maps_path
  pod 'GoogleMaps'  # Remove this line if you don't want to support Google Maps on iOS
  #pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support Google Maps on iOS
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end
